### ISSUE TITLE
Integrated browser

### ISSUE THREAD

**Issue by xunil89** [aerotoad/Thud#39]
As per the title, an integrated browser would be useful, perhaps with the option of forcing it into read mode as in the squid app, perhaps as the default view.

**Comment by xunil89** [comment]
![IMG_20220412_130259_554](https://user-images.githubusercontent.com/14961235/162946364-13907bac-db0e-4154-a22e-8a3cef448e75.jpg)
Example image of reading mode in firefox

**Comment by aerotoad** [comment]
The app already has an integrated browser, without a read mode, since that is the default view of the app itself.

You can open an article in the integrated browser using this button:

![IMG_20220412_131257.jpg](https://user-images.githubusercontent.com/5224455/162948101-126853a3-95ba-427e-b357-442e4c056a30.jpg)
![Screenshot_2022-04-12-13-10-54-634_com.android.chrome.jpg](https://user-images.githubusercontent.com/5224455/162948135-43680f28-08ab-4608-92b6-c81f92c5cade.jpg)

Or by clicking the "open in browser" button at the end of an article.

**Comment by xunil89** [comment]
> 

> The app already has an integrated browser, without a read mode, since that is the default view of the app itself.
> 
> You can open an article in the integrated browser using this button:
> 
> ![IMG_20220412_131257.jpg](https://user-images.githubusercontent.com/5224455/162948101-126853a3-95ba-427e-b357-442e4c056a30.jpg) ![Screenshot_2022-04-12-13-10-54-634_com.android.chrome.jpg](https://user-images.githubusercontent.com/5224455/162948135-43680f28-08ab-4608-92b6-c81f92c5cade.jpg)
> 
> Or by clicking the "open in browser" button at the end of an article.
Yes, I'm aware that there's already an integrated mini-browser, but it "limits" itself to reproducing the content of the feed. Some sites don't include the entire article in their feed, so you're "forced" to leave the app and go to a system browser.

**Comment by aerotoad** [comment]
Closing this since it's not an issue.
