### ISSUE TITLE
Feature Request: widget

### ISSUE THREAD

**Issue by akp37** [aerotoad/Thud#42]
Loving your app, great work thus far!
However, I was wondering if you were planning on adding a widget. 
It would be great if this was added!

**Comment by aerotoad** [comment]
I got this same request on the google play store a couple of times, and I looked into it.
The problem I got is that this app is built using capacitor as a native bridge and web technologies for the UI and logic, this approach doesn't allow for the creation of native android widgets.
There was a tool created by microsoft a few years ago that addressed this problem but it has been discontinued since.

If anyone can come up with a way to make this possible or want to create a PR with a solution, I'm open to it.
